# Site settings
title:       Akumuli
email:       https://groups.google.com/forum/#!forum/akumuli
author:      Eugene Lazin
description: "Time-series database."
baseurl:     ""
url:         "http://akumuli.org"

# Google analytics
google_analytics: "UA-47803053-1"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "akumuli"

# Social icons
show_social_icons: true
github_username: "Akumuli"
stackoverflow_id:
twitter_username: "Lazin"
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
kramdown:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
